# docker-compose.yml

version: '3'
services:
  xss:
    image: rust:1.53
    restart: always
    ports:
      - "80:80"
    volumes:
      - ".:/root/xss/"
      - "_cargo:/root/.cargo"
    working_dir: /root/xss/
    command: "/bin/bash -c \"cargo run\""
    depends_on:
      - db
  dbrest:
    image: postgrest/postgrest
    restart: always
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://web:123456@db:5432/postgres
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: web
      PGRST_JWT_SECRET: C4CA4238A0B923820DCC509A6F75849B
      PGRST_OPENAPI_SERVER_PROXY_URI: "http://127.0.0.1:3000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: web
      POSTGRES_PASSWORD: 123456
    volumes:
      - "/var/lib/postgresql/data:/var/lib/postgresql/data"
